env = "test" # "test", "dev", "prod"

[log]
# Log level: "trace", "debug", "info", "warn", "error"
level = "info"

[server]
# The address to bind to.
addr = ":8080"
# The maximum number of seconds to wait for graceful shutdown.
graceful_shutdown = 10

[redis]
prefix = "YWAPI:"
node = "127.0.0.1:6379"

[base]
userbase = "http://127.0.0.1:8080"
writing = "http://127.0.0.1:8080"
jarvis = "http://127.0.0.1:8080"
logbase = "http://127.0.0.1:8080"
taskbase = "http://127.0.0.1:8080"
webscraper = "http://127.0.0.1:8080"
walletbase = "http://127.0.0.1:8080"

[oss]
bucket = "ywfs"
endpoint = "oss-cn-hangzhou.aliyuncs.com"
access_key_id = ""
access_key_secret = ""
base_url = "https://fs.yiwen.pub/"

[wechat]
appid = ""
secret = ""

[tokens_rate]
English = 1.0
Chinese = 1.40
Afrikaans = 1.56
Aragonese = 1.45
Arabic = 2.60
Azerbaijani = 2.70
Assamese = 5.65
Belarusian = 3.00
Bengali = 5.38
Bislama = 1.58
Bosnian = 1.78
Breton = 1.71
Bulgarian = 2.16
Catalan = 1.67
Chamorro = 1.24
Czech = 1.98
Chechen = 1.98
"Church Slavic" = 1.98
Cornish = 1.94
Corsican = 1.85
Welsh = 2.04
Danish = 1.55
German = 1.39
Esperanto = 1.78
Estonian = 1.74
"Modern Greek" = 4.38
Faroese = 1.98
Persian = 2.91
Finnish = 1.86
French = 1.36
"Western Frisian" = 1.66
Basque = 1.85
Fulah = 1.77
Galician = 1.32
Irish = 2.15
"Scottish Gaelic" = 2.28
Gujarati = 7.30
Croatian = 1.78
Hungarian = 2.17
Hebrew = 3.40
Interlingua = 1.30
Hindi = 4.12
Indonesian = 1.44
Icelandic = 2.05
Italian = 1.49
Javanese = 1.68
Japanese = 1.95
Kazakh = 3.71
Kannada = 6.65
Kashmiri = 4.18
Korean = 1.92
Latvian = 2.14
Lithuanian = 1.98
Luxembourgish = 1.83
Macedonian = 2.32
Maltese = 2.34
Malagasy = 2.10
Malay = 1.68
Mongolian = 3.86
Dutch = 1.45
"Norwegian Bokmål" = 1.50
"Norwegian Nynorsk" = 1.52
Nepali = 4.53
Occitan = 1.69
Norwegian = 1.50
Polish = 1.67
Portuguese = 1.33
Panjabi = 6.95
Romansh = 1.56
Romanian = 1.74
Pushto = 3.43
Russian = 1.93
Slovak = 2.03
Slovenian = 1.74
Spanish = 1.27
Somali = 1.97
Albanian = 2.11
Serbian = 1.77
Sundanese = 1.70
Swahili = 1.76
Swedish = 1.49
Tagalog = 1.89
Thai = 3.39
Turkmen = 1.78
Turkish = 1.86
Ukrainian = 2.74
Urdu = 3.45
Uzbek = 2.26
Vietnamese = 2.22
Xhosa = 2.01
Yiddish = 3.42

[[recommendations]]
gid = "cil6ehjmps48vprp24f0"
cid = "cjoip8a7a762siruokm0"
